export enum PromptType {
  QUIZ_GENERATOR = 'QUIZ_GENERATOR',
  ASSIGNMENT_GENERATOR = 'ASSIGNMENT_GENERATOR',
  LESSON_SUMMARY = 'LESSON_SUMMARY',
  MATERIAL_TAGGING = 'MATERIAL_TAGGING',
  PROGRESS_ANALYSIS = 'PROGRESS_ANALYSIS',
  TEACHER_ASSISTANT = 'TEACHER_ASSISTANT',
}
